package com.sakhtyar.scenario.api;
import com.sakhtyar.material.domain.MaterialPriceType; import com.sakhtyar.scenario.domain.*; import jakarta.validation.constraints.*; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
public final class ScenarioDtos {
 private ScenarioDtos(){}
 public record UpsertPackageRequest(@NotBlank @Size(max=120) String code,@NotBlank @Size(max=400) String nameFa,@Size(max=400) String nameEn,@NotNull QualityLevel qualityLevel,@Size(max=10000) String description,boolean active,Map<String,Object> metadata){}
 public record CreateSelectionRequest(@NotBlank @Size(max=120) String slotCode,@NotBlank @Size(max=300) String slotNameFa,@NotNull UUID assemblyId,boolean required,@NotNull @DecimalMin("0.000001") BigDecimal quantityMultiplier,@Min(0) int sortOrder,@Size(max=4000) String note){}
 public record UpsertScenarioRequest(@NotBlank @Size(max=120) String code,@NotBlank @Size(max=400) String nameFa,@Size(max=400) String nameEn,UUID qualityPackageId,@Size(max=160) String structuralSystem,@Size(max=10000) String description,Map<String,Object> assumptions,boolean active){}
 public record CreateScenarioItemRequest(@Size(max=120) String slotCode,@NotNull UUID assemblyId,@NotNull @DecimalMin("0.000001") BigDecimal quantity,@NotNull ScenarioItemSource source,boolean enabled,@Min(0) int sortOrder,@Size(max=4000) String note){}
 public record ChangeStatusRequest(@NotNull ScenarioStatus status){}
 public record CalculateScenarioRequest(@NotNull MaterialPriceType priceType,@NotBlank @Size(min=3,max=3) String currencyCode,@Size(max=160) String province,@Size(max=160) String city){}
 public record PackageResponse(UUID id,String code,String nameFa,String nameEn,QualityLevel qualityLevel,String description,boolean active,Map<String,Object> metadata,String createdBy,Instant createdAt,Instant updatedAt){public static PackageResponse from(QualityPackageEntity e){return new PackageResponse(e.getId(),e.getCode(),e.getNameFa(),e.getNameEn(),e.getQualityLevel(),e.getDescription(),e.isActive(),e.getMetadata(),e.getCreatedBy(),e.getCreatedAt(),e.getUpdatedAt());}}
 public record SelectionResponse(UUID id,UUID packageId,String slotCode,String slotNameFa,UUID assemblyId,boolean required,BigDecimal quantityMultiplier,int sortOrder,String note,Instant createdAt){public static SelectionResponse from(QualityPackageSelectionEntity e){return new SelectionResponse(e.getId(),e.getPackageId(),e.getSlotCode(),e.getSlotNameFa(),e.getAssemblyId(),e.isRequired(),e.getQuantityMultiplier(),e.getSortOrder(),e.getNote(),e.getCreatedAt());}}
 public record ScenarioResponse(UUID id,String code,String nameFa,String nameEn,UUID qualityPackageId,String structuralSystem,ScenarioStatus status,String description,Map<String,Object> assumptions,boolean active,String createdBy,Instant createdAt,Instant updatedAt){public static ScenarioResponse from(ConstructionScenarioEntity e){return new ScenarioResponse(e.getId(),e.getCode(),e.getNameFa(),e.getNameEn(),e.getQualityPackageId(),e.getStructuralSystem(),e.getStatus(),e.getDescription(),e.getAssumptions(),e.isActive(),e.getCreatedBy(),e.getCreatedAt(),e.getUpdatedAt());}}
 public record ScenarioItemResponse(UUID id,UUID scenarioId,String slotCode,UUID assemblyId,BigDecimal quantity,ScenarioItemSource source,boolean enabled,int sortOrder,String note,Instant createdAt){public static ScenarioItemResponse from(ConstructionScenarioItemEntity e){return new ScenarioItemResponse(e.getId(),e.getScenarioId(),e.getSlotCode(),e.getAssemblyId(),e.getQuantity(),e.getSource(),e.isEnabled(),e.getSortOrder(),e.getNote(),e.getCreatedAt());}}
 public record SnapshotLineResponse(UUID id,UUID scenarioItemId,UUID assemblyId,UUID assemblyEstimateId,BigDecimal quantity,BigDecimal unitCost,BigDecimal lineTotal){public static SnapshotLineResponse from(ScenarioCostSnapshotLineEntity e){return new SnapshotLineResponse(e.getId(),e.getScenarioItemId(),e.getAssemblyId(),e.getAssemblyEstimateId(),e.getQuantity(),e.getUnitCost(),e.getLineTotal());}}
 public record SnapshotResponse(UUID id,UUID scenarioId,MaterialPriceType priceType,String currencyCode,String province,String city,BigDecimal totalCost,String algorithmVersion,String calculatedBy,Instant calculatedAt,List<SnapshotLineResponse> lines){}
}