package com.sakhtyar.agents.provider;
import java.time.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;
@Service public class AiGateway{
 private final JdbcTemplate jdbc;private final AiModelRegistry registry;public AiGateway(JdbcTemplate j,AiModelRegistry r){jdbc=j;registry=r;}
 public Optional<GatewayExecution> generate(String agent,AiModelProvider.AiModelRequest req){List<Target> ts=targets(agent);if(ts.isEmpty())return registry.activeProvider().map(p->execute(agent,p,false,req));RuntimeException last=null;boolean fb=false;for(Target t:ts){var p=registry.provider(t.code());if(p.isEmpty())continue;try{if(!p.get().available())continue;return Optional.of(execute(agent,p.get(),fb||t.fallback(),req));}catch(RuntimeException e){last=e;failure(agent,p.get(),fb||t.fallback(),e);}fb=true;}if(last!=null)throw last;return Optional.empty();}
 private List<Target> targets(String agent){var rows=jdbc.queryForList("select pp.code primary_provider,fp.code fallback_provider,cp.code canary_provider,r.canary_weight_percent from ai_agent_route r left join ai_provider pp on pp.id=r.primary_provider_id left join ai_provider fp on fp.id=r.fallback_provider_id left join ai_provider cp on cp.id=r.canary_provider_id where upper(r.agent_code)=upper(?) and r.enabled=true",agent);if(rows.isEmpty())return List.of();var r=rows.getFirst();String p=(String)r.get("primary_provider"),f=(String)r.get("fallback_provider"),c=(String)r.get("canary_provider");int w=r.get("canary_weight_percent")==null?0:((Number)r.get("canary_weight_percent")).intValue();ArrayList<Target>x=new ArrayList<>();if(c!=null&&w>0&&ThreadLocalRandom.current().nextInt(100)<w)x.add(new Target(c,true));if(p!=null)x.add(new Target(p,false));if(f!=null&&!f.equals(p))x.add(new Target(f,true));return x;}
 private GatewayExecution execute(String a,AiModelProvider p,boolean fb,AiModelProvider.AiModelRequest r){Instant s=Instant.now();var out=p.generate(r);long ms=Duration.between(s,Instant.now()).toMillis();jdbc.update("insert into ai_usage_event(id,agent_code,provider_code,model_code,success,fallback_used,latency_ms,input_tokens,output_tokens,observed_at) values(?,?,?,?,true,?,?,?,?,now())",UUID.randomUUID(),a,p.providerId(),out.model(),fb,ms,out.inputTokens(),out.outputTokens());return new GatewayExecution(out,p.providerId(),fb,ms);}
 private void failure(String a,AiModelProvider p,boolean fb,RuntimeException e){jdbc.update("insert into ai_usage_event(id,agent_code,provider_code,model_code,success,fallback_used,latency_ms,input_tokens,output_tokens,error_code,observed_at) values(?,?,?,?,false,?,0,0,0,?,now())",UUID.randomUUID(),a,p.providerId(),p.modelId(),fb,e.getClass().getSimpleName());}
 private record Target(String code,boolean fallback){} public record GatewayExecution(AiModelProvider.AiModelResponse response,String provider,boolean fallbackUsed,long latencyMs){}
}