spring:
  data:
    redis:
      password: ${REDIS_PASSWORD:}

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  observations:
    key-values:
      application: sakhtyar

logging:
  structured:
    format:
      console: logstash
