import { ApiOutlined,ExperimentOutlined,PlusOutlined,RobotOutlined,ThunderboltOutlined } from '@ant-design/icons'
import { Alert,Button,Card,Col,Descriptions,Empty,Form,Input,InputNumber,Modal,Progress,Row,Select,Space,Statistic,Switch,Table,Tabs,Tag,Typography } from 'antd'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { useMemo,useState } from 'react'
import { api } from '../api/client'
import { ContextHelpButton,type HelpTab } from '../ui/ContextHelpButton'
import { MetricLineChart } from '../ui/MetricLineChart'
import { AiPlaygroundPanel } from '../ui/AiPlaygroundPanel'
type Provider={id:string;code:string;display_name:string;provider_type:string;health_status:string;lifecycle_status:string;priority:number}
type Model={id:string;provider_id:string;provider_code:string;display_name:string;provider_model_id:string;supports_json:boolean;supports_tools:boolean;supports_vision:boolean}
const helpTabs:HelpTab[]=[
 {key:'intro',labelFa:'معرفی',labelEn:'Overview',articles:[
  {titleFa:'مرکز کنترل AI چیست؟',titleEn:'AI Control Center',bodyFa:'این بخش Control Plane هوش مصنوعی ساخت‌یار است. Agentها از طریق AI Gateway به Providerها متصل می‌شوند تا وابستگی مستقیم به Ollama یا سرویس Cloud نداشته باشند.\n\nچرخه اصلی: ارائه‌دهنده → مدل → مسیریابی عامل → پرامپت → اجرا → Usage/Latency/Error → ارزیابی کیفیت.',bodyEn:'AI control plane for providers, models, routes, prompts and telemetry.'}
 ]},
 {key:'concepts',labelFa:'مفاهیم',labelEn:'Concepts',articles:[
  {titleFa:'Primary / Fallback / Canary',titleEn:'Primary/Fallback/Canary',bodyFa:'Primary مسیر اصلی است.\nFallback هنگام خطای مسیر اصلی استفاده می‌شود.\nCanary درصد کمی از ترافیک را به مسیر آزمایشی می‌فرستد تا قبل از Rollout کامل ارزیابی شود.',bodyEn:'Primary is normal traffic, fallback handles failures, canary receives controlled experimental traffic.'},
  {titleFa:'Routing Strategy',titleEn:'Routing Strategy',bodyFa:'PRIMARY_FALLBACK اکنون در Runtime فعال است. LATENCY_AWARE، COST_AWARE و CAPABILITY_AWARE در Control Plane ثبت می‌شوند و اجرای کامل Runtime آن‌ها به‌صورت مرحله‌ای توسعه می‌یابد.',bodyEn:'Primary/fallback is active; advanced strategies are represented for progressive runtime rollout.'}
 ]},
 {key:'providers',labelFa:'ارائه‌دهنده و مدل',labelEn:'Providers & Models',articles:[
  {titleFa:'ارائه‌دهنده',titleEn:'Provider',bodyFa:'Provider موتور اجرای مدل است؛ مثل Ollama Local. ثبت Provider در دیتابیس به‌تنهایی Adapter اجرایی ایجاد نمی‌کند. Test Connection وجود Runtime Adapter و Health واقعی را بررسی می‌کند.',bodyEn:'A provider is a runtime; a registry row alone does not create an executable adapter.'},
  {titleFa:'قابلیت مدل',titleEn:'Capabilities',bodyFa:'JSON برای خروجی ساختاریافته، Tool Calling برای ابزارها، Vision برای تصویر و Embedding برای بردار است. این مشخصات پایه Capability-Aware Routing هستند.',bodyEn:'Capabilities power safe model selection.'}
 ]},
 {key:'routing',labelFa:'مسیریابی',labelEn:'Routing',articles:[
  {titleFa:'روش امن Rollout',titleEn:'Safe rollout',bodyFa:'۱) Provider و Model را تست کنید.\n۲) Fallback سالم تعریف کنید.\n۳) Canary را با ۵ تا ۱۰٪ شروع کنید.\n۴) Error، Latency و Quality را مقایسه کنید.\n۵) سپس سهم را تدریجی افزایش دهید.\n\nبرای داده حساس Local Only را فعال کنید.',bodyEn:'Test, configure fallback, start canary low, compare reliability/quality, then ramp.'}
 ]},
 {key:'prompts',labelFa:'پرامپت‌ها',labelEn:'Prompts',articles:[
  {titleFa:'نسخه‌بندی',titleEn:'Versioning',bodyFa:'هر تغییر Prompt باید نسخه جدید ایجاد کند. DRAFT، STAGING، PRODUCTION و ARCHIVED چرخه انتشار را کنترل می‌کنند و زمینه Rollback را فراهم می‌کنند.',bodyEn:'Versioning enables controlled promotion and rollback.'}
 ]},
 {key:'metrics',labelFa:'شاخص‌ها',labelEn:'Metrics',articles:[
  {titleFa:'Reliability و Performance',titleEn:'Reliability & Performance',bodyFa:'Requests، Success Rate، Fallback Rate، Average/P95 Latency، Tokens و Cost شاخص‌های عملیاتی هستند.\n\nProvider می‌تواند Healthy باشد ولی پاسخ ضعیف بدهد؛ بنابراین Quality باید جدا از Health زیرساخت اندازه‌گیری شود.',bodyEn:'Reliability and answer quality are different dimensions.'}
 ]},
 {key:'playground-help',labelFa:'آزمایشگاه',labelEn:'Playground',articles:[
  {titleFa:'آزمایشگاه چه کاری انجام می‌دهد؟',titleEn:'What does the playground do?',bodyFa:'یک درخواست واقعی را از همان AI Gateway و Route اجرایی Agent عبور می‌دهد. نتیجه Provider، Model، Latency، Token و Fallback را نشان می‌دهد و Usage واقعی تولید می‌کند.\n\nاین ابزار برای Smoke Test، بررسی Route و مشاهده سریع رفتار مدل است؛ برای داده‌های محرمانه Production از ورودی تستی و غیرحساس استفاده کنید.',bodyEn:'Runs a real request through the configured AI Gateway route and records real usage telemetry.'}
 ]}, {key:'tech',labelFa:'تکنولوژی‌ها',labelEn:'Technology',articles:[
  {titleFa:'AI Gateway + Java',titleEn:'AI Gateway + Java',bodyFa:'AI Gateway در Backend Java قرار دارد و Agent را از Provider جدا می‌کند. محاسبات قطعی کسب‌وکار همچنان در Java باقی می‌مانند.',bodyEn:'Java gateway decouples agents while deterministic logic stays in Java.'},
  {titleFa:'Ollama',titleEn:'Ollama',bodyFa:'Runtime محلی فعلی است. مدل، timeout و تنظیمات Performance از application.yml / Environment خوانده می‌شوند.',bodyEn:'Current local model runtime.'},
  {titleFa:'PostgreSQL',titleEn:'PostgreSQL',bodyFa:'Registry ارائه‌دهنده، مدل، Route، Prompt Version و AI Usage Event را ذخیره می‌کند.',bodyEn:'Stores control-plane configuration and usage events.'}
 ]},
 {key:'trouble',labelFa:'عیب‌یابی',labelEn:'Troubleshooting',articles:[
  {titleFa:'Provider قرمز است',titleEn:'Provider unhealthy',bodyFa:'Test Connection بزنید و Base URL، مدل و Runtime Adapter را بررسی کنید. Provider بدون Adapter Java فقط Registry دارد و قابل اجرا نیست.',bodyEn:'Check base URL, model and runtime adapter.'},
  {titleFa:'Usage صفر است',titleEn:'Usage is zero',bodyFa:'یک درخواست واقعی از Agent ارسال کنید. فقط فراخوانی‌های عبوری از AI Gateway در ai_usage_event ثبت می‌شوند؛ Agentهای deterministic الزاماً Usage AI تولید نمی‌کنند.',bodyEn:'Only real AI Gateway calls create usage events.'}
 ]}
]
const pct=(p:number,t:number)=>t<=0?0:(p/t)*100

export function AiManagementPage(){
 const qc=useQueryClient(),[po,setPo]=useState(false),[mo,setMo]=useState(false),[ro,setRo]=useState(false),[pro,setPro]=useState(false)
 const overview=useQuery({queryKey:['ai-overview-pro'],queryFn:()=>api<any>('/api/v1/admin/ai/overview'),refetchInterval:15000})
 const metrics=useQuery({queryKey:['ai-metrics-pro'],queryFn:()=>api<any>('/api/v1/admin/ai/metrics'),refetchInterval:15000})
 const providers=useQuery({queryKey:['ai-providers-pro'],queryFn:()=>api<Provider[]>('/api/v1/admin/ai/providers')})
 const models=useQuery({queryKey:['ai-models-pro'],queryFn:()=>api<Model[]>('/api/v1/admin/ai/models')})
 const routes=useQuery({queryKey:['ai-routes-pro'],queryFn:()=>api<any[]>('/api/v1/admin/ai/routes')})
 const agents=useQuery({queryKey:['ai-agents-pro'],queryFn:()=>api<any[]>('/api/v1/admin/ai/agents')})
 const prompts=useQuery({queryKey:['ai-prompts-pro'],queryFn:()=>api<any[]>('/api/v1/admin/ai/prompts')})
 const inv=()=>['ai-overview-pro','ai-metrics-pro','ai-providers-pro','ai-models-pro','ai-routes-pro','ai-prompts-pro'].forEach(k=>qc.invalidateQueries({queryKey:[k]}))
 const addProvider=useMutation({mutationFn:(v:any)=>api('/api/v1/admin/ai/providers',{method:'POST',body:JSON.stringify({...v,enabled:v.enabled??true,lifecycleStatus:v.lifecycleStatus??'DRAFT',priority:v.priority??100,requestTimeoutSeconds:v.requestTimeoutSeconds??90,environment:'LOCAL'})}),onSuccess:()=>{setPo(false);inv()}})
 const testProvider=useMutation({mutationFn:(id:string)=>api(`/api/v1/admin/ai/providers/${id}/test`,{method:'POST'}),onSuccess:inv})
 const addModel=useMutation({mutationFn:(v:any)=>api('/api/v1/admin/ai/models',{method:'POST',body:JSON.stringify({...v,enabled:true,supportsJson:v.supportsJson??false,supportsTools:v.supportsTools??false,supportsVision:v.supportsVision??false,supportsEmbeddings:false})}),onSuccess:()=>{setMo(false);inv()}})
 const saveRoute=useMutation({mutationFn:(v:any)=>api('/api/v1/admin/ai/routes',{method:'POST',body:JSON.stringify({...v,canaryWeightPercent:v.canaryWeightPercent??0,routingStrategy:v.routingStrategy??'PRIMARY_FALLBACK',timeoutSeconds:90,maxRetries:1,requireJson:v.requireJson??false,requireTools:false,requireVision:false,localOnly:v.localOnly??false,enabled:true})}),onSuccess:()=>{setRo(false);inv()}})
 const addPrompt=useMutation({mutationFn:(v:any)=>api('/api/v1/admin/ai/prompts',{method:'POST',body:JSON.stringify({...v,lifecycleStatus:v.lifecycleStatus??'DRAFT'})}),onSuccess:()=>{setPro(false);inv()}})
 const pops=(providers.data??[]).map(p=>({value:p.id,label:`${p.display_name} (${p.code})`}))
 const s=metrics.data?.summary??{},req=Number(s.requests??0),ok=Number(s.successes??0),fb=Number(s.fallbacks??0),success=pct(ok,req),fallback=pct(fb,req)
 const trendReq=useMemo(()=>(metrics.data?.trend??[]).map((r:any)=>({timestamp:r.bucket,value:Number(r.requests??0)})),[metrics.data])
 const trendLat=useMemo(()=>(metrics.data?.trend??[]).map((r:any)=>({timestamp:r.bucket,value:Number(r.avg_latency_ms??0)})),[metrics.data])
 const trendTok=useMemo(()=>(metrics.data?.trend??[]).map((r:any)=>({timestamp:r.bucket,value:Number(r.tokens??0)})),[metrics.data])
 const tabs=[
  {key:'overview',label:'نمای کلی',children:<div className="sakhtyar-dashboard-grid"><Row gutter={[12,12]}><Col xs={24} md={12} xl={6}><Card className="sakhtyar-kpi-card sakhtyar-kpi-primary"><Statistic title="درخواست AI در ۲۴ ساعت" value={req} prefix={<RobotOutlined/>}/><div className="sakhtyar-kpi-foot">رخداد واقعی AI Gateway</div></Card></Col><Col xs={24} md={12} xl={6}><Card className="sakhtyar-kpi-card"><Statistic title="نرخ موفقیت" value={success} precision={1} suffix="٪"/><Progress percent={Math.min(100,success)} size="small" showInfo={false}/></Card></Col><Col xs={24} md={12} xl={6}><Card className="sakhtyar-kpi-card"><Statistic title="P95 زمان پاسخ AI" value={Number(s.p95_latency_ms??0)} precision={0} suffix="ms"/><div className="sakhtyar-kpi-foot">Tail Latency</div></Card></Col><Col xs={24} md={12} xl={6}><Card className="sakhtyar-kpi-card"><Statistic title="نرخ Fallback" value={fallback} precision={1} suffix="٪"/><div className="sakhtyar-kpi-foot">استفاده از مسیر جایگزین</div></Card></Col></Row><Row gutter={[12,12]}><Col xs={24} xl={8}><MetricLineChart title="ترافیک AI" subtitle="درخواست در ساعت" points={trendReq}/></Col><Col xs={24} xl={8}><MetricLineChart title="میانگین زمان پاسخ" subtitle="Latency" unit="ms" points={trendLat}/></Col><Col xs={24} xl={8}><MetricLineChart title="مصرف Token" subtitle="Input + Output" points={trendTok}/></Col></Row><Card title="وضعیت Control Plane"><Row gutter={[16,16]}><Col xs={24} md={6}><Statistic title="ارائه‌دهنده‌ها" value={overview.data?.providers??0} prefix={<ApiOutlined/>}/></Col><Col xs={24} md={6}><Statistic title="مدل‌ها" value={overview.data?.models??0} prefix={<RobotOutlined/>}/></Col><Col xs={24} md={6}><Statistic title="مسیرهای عامل" value={overview.data?.routes??0} prefix={<ThunderboltOutlined/>}/></Col><Col xs={24} md={6}><Statistic title="پرامپت‌ها" value={overview.data?.prompts??0} prefix={<ExperimentOutlined/>}/></Col></Row></Card></div>},
  {key:'providers',label:'ارائه‌دهنده‌ها',children:<div className="sakhtyar-dashboard-grid"><div className="sakhtyar-section-actions"><Typography.Title level={4} style={{margin:0}}>ارائه‌دهنده‌های مدل</Typography.Title><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setPo(true)}>ارائه‌دهنده جدید</Button></div><div className="sakhtyar-provider-grid">{(providers.data??[]).map(p=>{const a=(metrics.data?.providerAnalytics??[]).find((x:any)=>x.provider_code===p.code),n=Number(a?.requests??0),suc=Number(a?.successes??0);return <Card key={p.id} className="sakhtyar-provider-card"><div className="sakhtyar-provider-card-head"><div><Typography.Title level={4} style={{margin:0}}>{p.display_name}</Typography.Title><Typography.Text type="secondary">{p.provider_type} · {p.code}</Typography.Text></div><Tag color={p.health_status==='HEALTHY'?'green':'red'}>{p.health_status==='HEALTHY'?'سالم':p.health_status}</Tag></div><Descriptions column={1} size="small"><Descriptions.Item label="Lifecycle">{p.lifecycle_status}</Descriptions.Item><Descriptions.Item label="درخواست ۲۴ ساعت">{n}</Descriptions.Item><Descriptions.Item label="نرخ موفقیت">{n?`${pct(suc,n).toFixed(1)}%`:'—'}</Descriptions.Item><Descriptions.Item label="P95">{a?.p95_latency_ms==null?'—':`${Number(a.p95_latency_ms).toFixed(0)} ms`}</Descriptions.Item></Descriptions><Button block loading={testProvider.isPending} onClick={()=>testProvider.mutate(p.id)}>تست اتصال</Button></Card>})}</div></div>},
  {key:'models',label:'مدل‌ها',children:<Card extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setMo(true)}>مدل جدید</Button>}><Table rowKey="id" pagination={false} dataSource={models.data??[]} columns={[{title:'مدل',dataIndex:'display_name'},{title:'ارائه‌دهنده',dataIndex:'provider_code'},{title:'شناسه Runtime',dataIndex:'provider_model_id'},{title:'JSON',dataIndex:'supports_json',render:(v:boolean)=>v?<Tag color="green">دارد</Tag>:<Tag>ندارد</Tag>},{title:'Tool Calling',dataIndex:'supports_tools',render:(v:boolean)=>v?<Tag color="green">دارد</Tag>:<Tag>ندارد</Tag>},{title:'Vision',dataIndex:'supports_vision',render:(v:boolean)=>v?<Tag color="green">دارد</Tag>:<Tag>ندارد</Tag>}]}/></Card>},
  {key:'agents',label:'عامل‌ها',children:<Row gutter={[12,12]}>{(agents.data??[]).map((a:any)=>{const m=(metrics.data?.agentAnalytics??[]).find((x:any)=>String(x.agent_code).toUpperCase()===String(a.type).toUpperCase());return <Col xs={24} md={12} xl={8} key={a.type}><Card className="sakhtyar-agent-card"><Typography.Title level={4}>{a.name}</Typography.Title><Tag>{a.type}</Tag><Typography.Paragraph type="secondary">{(a.capabilities??[]).join(' · ')}</Typography.Paragraph><Descriptions column={1} size="small"><Descriptions.Item label="Provider">{a.provider}</Descriptions.Item><Descriptions.Item label="Timeout">{a.timeoutSeconds}s</Descriptions.Item><Descriptions.Item label="درخواست AI">{m?.requests??0}</Descriptions.Item><Descriptions.Item label="P95">{m?.p95_latency_ms==null?'—':`${Number(m.p95_latency_ms).toFixed(0)} ms`}</Descriptions.Item></Descriptions></Card></Col>})}</Row>},
  {key:'routing',label:'مسیریابی عامل‌ها',children:<div className="sakhtyar-dashboard-grid"><Alert showIcon type="info" message="برای Rollout امن، Canary را با ۵ تا ۱۰٪ شروع کنید و قبل از افزایش سهم Error/Latency/Quality را بررسی کنید."/><div className="sakhtyar-section-actions"><Typography.Title level={4} style={{margin:0}}>نقشه مسیرها</Typography.Title><Button type="primary" onClick={()=>setRo(true)}>تنظیم مسیر</Button></div>{(routes.data??[]).length?<div className="sakhtyar-routing-grid">{routes.data!.map((r:any)=><Card key={r.id} className="sakhtyar-routing-card"><Typography.Title level={4}>{r.agent_code}</Typography.Title><div className="sakhtyar-routing-flow"><div className="route-node">عامل</div><div className="route-arrow">←</div><div className="route-node route-primary">اصلی<strong>{r.primary_provider_code||'—'}</strong></div>{r.canary_provider_code?<><div className="route-arrow">+ {r.canary_weight_percent}%</div><div className="route-node route-canary">Canary<strong>{r.canary_provider_code}</strong></div></>:null}{r.fallback_provider_code?<><div className="route-arrow">در خطا ←</div><div className="route-node route-fallback">جایگزین<strong>{r.fallback_provider_code}</strong></div></>:null}</div><Space wrap><Tag>{r.routing_strategy}</Tag>{r.local_only?<Tag color="purple">فقط Local</Tag>:null}{r.require_json?<Tag color="blue">JSON اجباری</Tag>:null}</Space></Card>)}</div>:<Empty description="هنوز Route ثبت نشده است"/>}</div>},
  {key:'prompts',label:'پرامپت‌ها',children:<Card extra={<Button type="primary" onClick={()=>setPro(true)}>نسخه جدید پرامپت</Button>}><Table rowKey="id" pagination={false} dataSource={prompts.data??[]} columns={[{title:'پرامپت',dataIndex:'display_name'},{title:'عامل',dataIndex:'agent_code'},{title:'نسخه',dataIndex:'version_no'},{title:'وضعیت',dataIndex:'lifecycle_status',render:(v:string)=><Tag>{v||'—'}</Tag>},{title:'یادداشت تغییر',dataIndex:'change_note'}]}/></Card>},
  {key:'playground',label:'آزمایشگاه',children:<AiPlaygroundPanel/>},
  {key:'quality',label:'کیفیت',children:<Card title="مرکز کیفیت AI"><Alert type="info" showIcon message="کیفیت با Health زیرساخت متفاوت است" description={metrics.data?.qualityMessage??'داده ارزیابی کیفیت هنوز Instrument نشده است.'}/><Row gutter={[12,12]} style={{marginTop:16}}>{['اعتبار JSON','دقت استخراج','نرخ اصلاح کاربر','دقت حوزه قضایی'].map(n=><Col xs={24} md={12} xl={6} key={n}><Card><Statistic title={n} value="—"/><Typography.Text type="secondary">نیازمند Evaluation Event واقعی</Typography.Text></Card></Col>)}</Row></Card>},
  {key:'usage',label:'مصرف و عملکرد',children:<Card><Table rowKey={(r:any,i?:number)=>`${r.provider_code}-${r.model_code}-${i}`} pagination={false} dataSource={metrics.data?.providerAnalytics??[]} columns={[{title:'ارائه‌دهنده',dataIndex:'provider_code'},{title:'مدل',dataIndex:'model_code'},{title:'درخواست',dataIndex:'requests'},{title:'موفق',dataIndex:'successes'},{title:'Fallback',dataIndex:'fallbacks'},{title:'میانگین زمان پاسخ',dataIndex:'avg_latency_ms',render:(v:number)=>`${Number(v??0).toFixed(0)} ms`},{title:'P95',dataIndex:'p95_latency_ms',render:(v:number)=>`${Number(v??0).toFixed(0)} ms`},{title:'Token',dataIndex:'total_tokens'}]}/></Card>}
 ]
 return <div className="sakhtyar-page-stack"><Card className="sakhtyar-dashboard-hero"><Space style={{width:'100%',justifyContent:'space-between'}} align="start" wrap><div><Typography.Title level={2} style={{margin:0}}>مرکز کنترل هوش مصنوعی</Typography.Title><Typography.Paragraph type="secondary" style={{marginBottom:0}}>مدیریت ارائه‌دهنده، مدل، عامل، مسیریابی، پرامپت، مصرف و کیفیت</Typography.Paragraph></div><ContextHelpButton titleFa="راهنمای جامع مدیریت هوش مصنوعی" titleEn="AI Control Center Guide" tabs={helpTabs}/></Space></Card><Tabs items={tabs}/>
 <Modal open={po} footer={null} onCancel={()=>setPo(false)} title="افزودن ارائه‌دهنده"><Form layout="vertical" onFinish={v=>addProvider.mutate(v)} initialValues={{providerType:'OLLAMA',enabled:true,lifecycleStatus:'DRAFT',priority:100,requestTimeoutSeconds:90}}><Form.Item name="code" label="کد" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="displayName" label="نام نمایشی" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="providerType" label="نوع"><Select options={[{value:'OLLAMA',label:'Ollama'},{value:'OPENAI_COMPATIBLE',label:'OpenAI Compatible'}]}/></Form.Item><Form.Item name="baseUrl" label="آدرس پایه"><Input/></Form.Item><Form.Item name="lifecycleStatus" label="چرخه عمر"><Select options={['DRAFT','TESTED','ACTIVE','DISABLED'].map(value=>({value,label:value}))}/></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="priority" label="اولویت"><InputNumber style={{width:'100%'}}/></Form.Item></Col><Col span={12}><Form.Item name="requestTimeoutSeconds" label="مهلت پاسخ"><InputNumber style={{width:'100%'}}/></Form.Item></Col></Row><Form.Item name="enabled" label="فعال" valuePropName="checked"><Switch/></Form.Item><Button htmlType="submit" type="primary">ذخیره</Button></Form></Modal>
 <Modal open={mo} footer={null} onCancel={()=>setMo(false)} title="افزودن مدل"><Form layout="vertical" onFinish={v=>addModel.mutate(v)}><Form.Item name="providerId" label="ارائه‌دهنده" rules={[{required:true}]}><Select options={pops}/></Form.Item><Form.Item name="code" label="کد" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="displayName" label="نام نمایشی" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="providerModelId" label="شناسه مدل در Runtime" rules={[{required:true}]}><Input/></Form.Item><Space wrap><Form.Item name="supportsJson" valuePropName="checked"><Switch/> JSON</Form.Item><Form.Item name="supportsTools" valuePropName="checked"><Switch/> Tool Calling</Form.Item><Form.Item name="supportsVision" valuePropName="checked"><Switch/> Vision</Form.Item></Space><Button htmlType="submit" type="primary">ذخیره</Button></Form></Modal>
 <Modal open={ro} footer={null} onCancel={()=>setRo(false)} title="تنظیم مسیر عامل"><Form layout="vertical" onFinish={v=>saveRoute.mutate(v)} initialValues={{routingStrategy:'PRIMARY_FALLBACK',canaryWeightPercent:0}}><Form.Item name="agentCode" label="عامل" rules={[{required:true}]}><Select options={(agents.data??[]).map((a:any)=>({value:a.type,label:`${a.name} (${a.type})`}))}/></Form.Item><Form.Item name="primaryProviderId" label="ارائه‌دهنده اصلی" rules={[{required:true}]}><Select options={pops}/></Form.Item><Form.Item name="fallbackProviderId" label="ارائه‌دهنده جایگزین"><Select allowClear options={pops}/></Form.Item><Form.Item name="canaryProviderId" label="ارائه‌دهنده Canary"><Select allowClear options={pops}/></Form.Item><Form.Item name="canaryWeightPercent" label="درصد Canary"><InputNumber min={0} max={100}/></Form.Item><Form.Item name="routingStrategy" label="استراتژی"><Select options={['PRIMARY_FALLBACK','LATENCY_AWARE','COST_AWARE','CAPABILITY_AWARE'].map(value=>({value,label:value}))}/></Form.Item><Space><Form.Item name="requireJson" valuePropName="checked"><Switch/> JSON اجباری</Form.Item><Form.Item name="localOnly" valuePropName="checked"><Switch/> فقط Local</Form.Item></Space><Button htmlType="submit" type="primary">ذخیره مسیر</Button></Form></Modal>
 <Modal open={pro} footer={null} onCancel={()=>setPro(false)} title="نسخه جدید پرامپت" width={760}><Form layout="vertical" onFinish={v=>addPrompt.mutate(v)} initialValues={{lifecycleStatus:'DRAFT'}}><Form.Item name="code" label="کد پرامپت" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="displayName" label="نام" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="agentCode" label="عامل"><Select allowClear options={(agents.data??[]).map((a:any)=>({value:a.type,label:a.name}))}/></Form.Item><Form.Item name="lifecycleStatus" label="وضعیت"><Select options={['DRAFT','STAGING','PRODUCTION','ARCHIVED'].map(value=>({value,label:value}))}/></Form.Item><Form.Item name="systemPrompt" label="System Prompt" rules={[{required:true}]}><Input.TextArea rows={10}/></Form.Item><Form.Item name="changeNote" label="یادداشت تغییر"><Input/></Form.Item><Button htmlType="submit" type="primary">ایجاد نسخه</Button></Form></Modal>
 </div>
}