import {ApiOutlined,ApartmentOutlined,BookOutlined,CheckCircleOutlined,DatabaseOutlined,PlayCircleOutlined,RobotOutlined,SearchOutlined,SettingOutlined,ToolOutlined} from '@ant-design/icons'
import {Alert,Button,Card,Collapse,Input,Space,Steps,Tag,Typography} from 'antd'
import {useMemo,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {useI18n} from '../i18n/LanguageProvider'
import './HelpCenterPage.css'

type Lesson={key:string;fa:string;en:string;dfa:string;den:string;route?:string;actionFa?:string;actionEn?:string;icon:string;sf:string[];se:string[];tags:string[]}
const lessons:Lesson[]=[
 {key:'start',fa:'شروع کار با ساخت‌یار',en:'Getting started',dfa:'از ورود تا ایجاد پرونده و مشاهده تحلیل.',den:'From sign-in to a case and its analysis.',route:'/cases',actionFa:'رفتن به پرونده‌ها',actionEn:'Open cases',icon:'play',tags:['کاربر','شروع'],sf:['تنظیمات زبان و کشور را بررسی کنید.','یک پرونده ایجاد کنید.','اطلاعات ملک، مالکین و مدارک را تکمیل کنید.','نتایج تحلیل را بررسی کنید.'],se:['Verify language and country settings.','Create a case.','Complete property, owner and document information.','Review analysis results.']},
 {key:'config',fa:'مرکز پیکربندی',en:'Configuration Center',dfa:'نسخه‌بندی، Secret، تست اتصال، Doctor و انتشار.',den:'Versioning, secrets, connection tests, Doctor and publishing.',route:'/admin/config',actionFa:'باز کردن مرکز پیکربندی',actionEn:'Open configuration',icon:'settings',tags:['مدیر','تنظیمات'],sf:['مقدار مؤثر و منبع هر تنظیم را ببینید.','برای تغییرات یک پیش‌نویس بسازید.','Secretها را از مسیر امن جایگزین کنید.','قبل از انتشار Config Doctor را اجرا کنید.'],se:['Review effective values and sources.','Create a draft for changes.','Replace secrets through the secure flow.','Run Config Doctor before publishing.']},
 {key:'automation',fa:'اتوماسیون و تعمیر محیط',en:'Automation & Runtime',dfa:'بررسی ابزارها، dependencyها، مخزن محلی، OCR و سلامت Runtime.',den:'Tools, dependencies, local repository, OCR and runtime health.',route:'/admin/config',actionFa:'باز کردن اتوماسیون',actionEn:'Open automation',icon:'tool',tags:['مدیر','Runtime','OCR'],sf:['بررسی همه را اجرا کنید.','موارد ناقص یا ناموفق را بررسی کنید.','تعمیر و نصب موارد ناقص را اجرا کنید.','بعد از سلامت محیط همان Execution را Resume کنید.'],se:['Run Check all.','Review missing or failed items.','Run Repair / install missing.','Resume the same execution when healthy.']},
 {key:'knowledge',fa:'مرکز دانش و پردازش اسناد',en:'Knowledge Center',dfa:'Discovery، انتخاب اسناد، OCR، کنترل کیفیت و انتشار Knowledge Release.',den:'Discovery, selection, OCR, quality gates and Knowledge Release.',route:'/knowledge',actionFa:'باز کردن مرکز دانش',actionEn:'Open knowledge center',icon:'book',tags:['دانش','Pipeline'],sf:['پوشه منبع را Discover کنید.','فقط اسناد لازم را انتخاب و Selection را Freeze کنید.','Pipeline از استخراج Native تا OCR و نرمال‌سازی ادامه می‌یابد.','در خطا همان Execution را Retry/Resume کنید.'],se:['Discover a source folder.','Select documents and freeze the selection.','Pipeline proceeds through native extraction, OCR and normalization.','Retry/Resume the same execution after failure.']},
 {key:'ai',fa:'هوش مصنوعی و مدل‌های محلی',en:'AI & local models',dfa:'لایه AI به‌صورت Local-first طراحی شده و Ollama میزبان مدل‌های محلی است؛ تنظیم مدل از Configuration انجام می‌شود.',den:'The AI layer is local-first; Ollama hosts local models and model selection is configuration-driven.',route:'/admin/ai',actionFa:'باز کردن مدیریت AI',actionEn:'Open AI management',icon:'robot',tags:['AI','Ollama','Local-first'],sf:['ابتدا قابلیت‌های قطعی و Rule-based اجرا می‌شوند.','مدل‌های سبک و استخراجگرهای تخصصی در صورت نیاز وارد می‌شوند.','LLM محلی برای مسائل مبهم‌تر یا تولیدی استفاده می‌شود.','سلامت provider و مدل را قبل از Workflowهای وابسته بررسی کنید.'],se:['Deterministic and rule-based capabilities run first.','Small/specialized extractors are preferred when sufficient.','A local LLM is used for more ambiguous or generative tasks.','Verify provider/model health before dependent workflows.']},
 {key:'agents',fa:'Agentها و Workflowهای هوشمند',en:'Agents & intelligent workflows',dfa:'Agentها مصرف‌کننده سرویس‌های تخصصی هستند و باید Workflow قابل‌ردیابی بسازند؛ منطق استخراج در Agent تکرار نمی‌شود.',den:'Agents compose specialized services into traceable workflows instead of duplicating extraction logic.',route:'/admin/ai',actionFa:'مشاهده مدیریت AI',actionEn:'Open AI management',icon:'api',tags:['Agent','Workflow','Audit'],sf:['هر Agent هدف و ورودی/خروجی مشخص دارد.','ابزارهای مشترک از سرویس‌های Intelligence و Knowledge مصرف می‌شوند.','خروجی‌ها باید provenance و evidence داشته باشند.','Workflowها برای Retry/Resume و Audit طراحی می‌شوند.'],se:['Each agent has explicit goals and inputs/outputs.','Shared tools come from Intelligence and Knowledge services.','Outputs should preserve provenance and evidence.','Workflows are designed for Retry/Resume and auditability.']},
 {key:'architecture',fa:'معماری فنی ساخت‌یار',en:'SakhtYar architecture',dfa:'Backend ماژولار، Frontend React، پایگاه داده PostgreSQL و سرویس‌های زیرساختی قابل جداسازی هستند.',den:'A modular backend, React frontend, PostgreSQL and separable infrastructure services.',icon:'architecture',tags:['معماری','Backend','Frontend'],sf:['Backend فعلی یک Modular Monolith با مرز ماژول‌هاست.','Config و Automation قابلیت‌های Platform-level هستند.','Knowledge و Intelligence مسئول دانش و پردازش هوشمندند.','مرزها طوری نگه داشته می‌شوند که سرویس‌ها در آینده قابل جداسازی باشند.'],se:['The backend is currently a modular monolith with module boundaries.','Config and Automation are platform-level capabilities.','Knowledge and Intelligence own knowledge and intelligent processing.','Boundaries are kept suitable for future service extraction.']},
 {key:'data',fa:'داده، Knowledge Graph و بازیابی',en:'Data, graph & retrieval',dfa:'دانش ساختاریافته با provenance نگهداری می‌شود و بازیابی ترکیبی می‌تواند SQL، متن، Graph و در آینده vector را ترکیب کند.',den:'Structured knowledge preserves provenance; hybrid retrieval can combine SQL, text, graph and optional vectors.',route:'/knowledge',actionFa:'مشاهده مرکز دانش',actionEn:'Open knowledge center',icon:'database',tags:['Graph','RAG','Provenance'],sf:['اصل سند و متن استخراج‌شده حفظ می‌شوند.','قواعد، تعاریف و روابط به دانش ساختاریافته تبدیل می‌شوند.','Graph یک projection از دانش canonical است.','Agentها فقط Knowledge Release نسخه‌بندی‌شده را مصرف می‌کنند.'],se:['Original sources and extracted text are preserved.','Rules, definitions and relations become structured knowledge.','The graph is a projection of canonical knowledge.','Agents consume versioned Knowledge Releases.']}
]
function LessonIcon({kind}:{kind:string}){if(kind==='robot')return <RobotOutlined/>;if(kind==='api')return <ApiOutlined/>;if(kind==='architecture')return <ApartmentOutlined/>;if(kind==='database')return <DatabaseOutlined/>;if(kind==='settings')return <SettingOutlined/>;if(kind==='tool')return <ToolOutlined/>;if(kind==='book')return <BookOutlined/>;return <PlayCircleOutlined/>}
export function HelpCenterPage(){
 const {language}=useI18n(),fa=language==='fa';const navigate=useNavigate();const [q,setQ]=useState('')
 const visible=useMemo(()=>lessons.filter(x=>`${x.fa} ${x.en} ${x.dfa} ${x.den} ${x.tags.join(' ')}`.toLowerCase().includes(q.toLowerCase())),[q])
 return <div className="sy-help" dir={fa?'rtl':'ltr'}>
  <div className="sy-help-hero"><Space><div className="sy-help-icon"><BookOutlined/></div><div><Typography.Title level={2}>{fa?'مرکز آموزش ساخت‌یار':'SakhtYar Help Center'}</Typography.Title><Typography.Text>{fa?'راهنمای عملی محصول، معماری، AI، Agentها و پردازش دانش':'Practical product, architecture, AI, agents and knowledge guide'}</Typography.Text></div></Space><Input allowClear prefix={<SearchOutlined/>} value={q} onChange={e=>setQ(e.target.value)} placeholder={fa?'جستجو در آموزش‌ها...':'Search help...'}/></div>
  <Alert showIcon type="info" message={fa?'دکمه‌های هر آموزش شما را مستقیماً به بخش مرتبط می‌برند.':'Each lesson action opens its related product area.'}/>
  <div className="sy-help-grid">{visible.map(x=><Card key={x.key} className="sy-help-card" title={<Space><LessonIcon kind={x.icon}/><span>{fa?x.fa:x.en}</span></Space>} extra={x.route?<Button type="link" onClick={()=>navigate(x.route!)}>{fa?x.actionFa:x.actionEn}</Button>:undefined}><Typography.Paragraph type="secondary">{fa?x.dfa:x.den}</Typography.Paragraph><Space wrap>{x.tags.map(t=><Tag key={t}>{t}</Tag>)}</Space><Steps direction="vertical" size="small" current={4} items={(fa?x.sf:x.se).map(v=>({title:v,icon:<CheckCircleOutlined/>}))}/></Card>)}</div>
  <Card title={fa?'سؤالات پرتکرار':'Frequently asked questions'}><Collapse ghost items={[
   {key:'1',label:fa?'چرا مراحل داخل کارت‌ها لینک نبودند؟':'Why were lesson steps not links?',children:fa?'در نسخه جدید، هر کارت یک اقدام واقعی برای رفتن به بخش مرتبط دارد؛ خود مراحل توضیح فرآیند هستند.':'Each card now has a real navigation action; steps describe the workflow.'},
   {key:'2',label:fa?'بعد از خطای Pipeline اجرای جدید بسازم؟':'Create a new run after pipeline failure?',children:fa?'خیر؛ تا وقتی Selection تغییر نکرده همان Execution را Retry/Resume کنید.':'No. Retry/Resume the same execution unless selection changed.'},
   {key:'3',label:fa?'Agent چه تفاوتی با سرویس Intelligence دارد؟':'How is an Agent different from an Intelligence service?',children:fa?'سرویس Intelligence یک قابلیت قابل‌استفاده مجدد ارائه می‌کند؛ Agent چند قابلیت و منبع دانش را برای رسیدن به یک هدف Workflow ترکیب می‌کند.':'An Intelligence service provides a reusable capability; an Agent composes capabilities and knowledge into a goal-oriented workflow.'}
  ]}/></Card>
 </div>
}
