import { CheckCircleOutlined,DashboardOutlined,ExclamationCircleOutlined,LinkOutlined,ReloadOutlined,SearchOutlined,WarningOutlined } from '@ant-design/icons'
import { Alert,Button,Card,Col,Descriptions,Empty,Input,Row,Segmented,Space,Statistic,Table,Tabs,Tag,Typography } from 'antd'
import { useQuery } from '@tanstack/react-query'
import { useMemo,useState } from 'react'
import { api } from '../api/client'
import { ContextHelpButton,type HelpTab } from '../ui/ContextHelpButton'
import { MetricLineChart } from '../ui/MetricLineChart'

const helpTabs:HelpTab[]=[
 {key:'intro',labelFa:'معرفی',labelEn:'Overview',articles:[
  {titleFa:'مرکز عملیات چه کاری انجام می‌دهد؟',titleEn:'Purpose',bodyFa:'این صفحه خلاصه مدیریتی وضعیت واقعی ساخت‌یار است. داده‌ها از Health Checkهای Backend، Prometheus، Loki و Tempo می‌آیند و Grafana فقط برای بررسی عمیق استفاده می‌شود.\n\nهدف این است که سریع بفهمیم: هسته سالم است؟ کاربران خطا می‌بینند؟ کندی داریم؟ مشکل مربوط به خود سامانه است یا فقط ابزار پایش؟',bodyEn:'Operational summary over backend health and observability sources.'},
  {titleFa:'سه حوزه سلامت',titleEn:'Health domains',bodyFa:'هسته: API، PostgreSQL، Redis، MinIO.\nAI: Provider فعال.\nپایش: Prometheus، Loki، Tempo، Grafana.\n\nخرابی Grafana به معنی Down بودن ساخت‌یار نیست و فقط دید فنی را کاهش می‌دهد.',bodyEn:'Core, AI and observability health are evaluated separately.'}
 ]},
 {key:'metrics',labelFa:'شاخص‌ها',labelEn:'Metrics',articles:[
  {titleFa:'RED',titleEn:'RED',bodyFa:'Rate = نرخ درخواست.\nErrors = درصد خطای 5xx.\nDuration = زمان پاسخ و به‌خصوص P95.\nاین سه شاخص وضعیت سرویس از نگاه کاربر را خلاصه می‌کنند.',bodyEn:'Rate, Errors and Duration.'},
  {titleFa:'USE',titleEn:'USE',bodyFa:'Utilization = مصرف منبع.\nSaturation = فشار/صف.\nErrors = خطاهای منبع.\nبرای JVM، CPU و Connection Pool به کار می‌رود.',bodyEn:'Utilization, Saturation and Errors.'},
  {titleFa:'P95 چیست؟',titleEn:'P95',bodyFa:'P95 یعنی ۹۵٪ درخواست‌ها سریع‌تر از این مقدار پاسخ گرفته‌اند و ۵٪ کندتر بوده‌اند. برای Tail Latency از Average مفیدتر است.',bodyEn:'95th percentile latency.'}
 ]},
 {key:'usage',labelFa:'نحوه استفاده',labelEn:'How to use',articles:[
  {titleFa:'روال بررسی',titleEn:'Workflow',bodyFa:'۱) وضعیت کل، هسته، AI و پایش را ببینید.\n۲) نرخ خطا و P95 را بررسی کنید.\n۳) اگر کندی دارید، Endpointهای کند و زیرساخت را ببینید.\n۴) اگر خطا دارید، مرکز رخدادها را بررسی کنید.\n۵) برای یک درخواست خاص Correlation ID را جست‌وجو کنید.\n۶) برای Deep Dive، Grafana را باز کنید.',bodyEn:'Review health, RED metrics, incidents, correlation and then Grafana.'}
 ]},
 {key:'tech',labelFa:'تکنولوژی‌ها',labelEn:'Technology',articles:[
  {titleFa:'Prometheus',titleEn:'Prometheus',bodyFa:'Metricهای Time-Series از Micrometer/Actuator را نگه می‌دارد. نمودارهای Rate، Error، Latency، JVM و DB Pool از آن می‌آیند.',bodyEn:'Time-series metrics backend.'},
  {titleFa:'Loki',titleEn:'Loki',bodyFa:'لاگ‌های ساخت‌یافته را نگه می‌دارد و برای Incident/Correlation Search استفاده می‌شود.',bodyEn:'Structured log backend.'},
  {titleFa:'Tempo + OpenTelemetry',titleEn:'Tempo + OpenTelemetry',bodyFa:'Traceهای توزیع‌شده را نگه می‌دارند. Service Graph و مسیرهای کند از این داده‌ها قابل استخراج‌اند.',bodyEn:'Distributed tracing.'},
  {titleFa:'Grafana',titleEn:'Grafana',bodyFa:'کنسول Deep Dive است و داخل ساخت‌یار Embed نشده. آدرس Local فعلی این سیستم http://localhost:13001 است.',bodyEn:'Deep-dive console; local port 13001.'}
 ]},
 {key:'trouble',labelFa:'عیب‌یابی',labelEn:'Troubleshooting',articles:[
  {titleFa:'اگر سرویس قرمز شد',titleEn:'Unhealthy service',bodyFa:'اول گروه سرویس را ببینید. Core می‌تواند اثر مستقیم روی کاربر داشته باشد. Observability معمولاً Warning است. برای Grafana ابتدا /api/health روی پورت 13001 را بررسی کنید.',bodyEn:'Check service group and impact before escalating.'}
 ]}
]
const statusTag=(s?:string)=>{const m:any={HEALTHY:['green','سالم'],DEGRADED:['gold','کاهش کیفیت'],UNHEALTHY:['red','ناسالم'],UNAVAILABLE:['red','در دسترس نیست']};const x=m[s??'']??['default',s??'نامشخص'];return <Tag color={x[0]}>{x[1]}</Tag>}
const mb=(v?:number|null)=>v==null||!Number.isFinite(Number(v))?'—':`${(Number(v)/1024/1024).toFixed(1)} MB`

export function OperationsPage(){
 const [range,setRange]=useState('6h'),[cid,setCid]=useState('')
 const summary=useQuery({queryKey:['ops-summary-pro'],queryFn:()=>api<any>('/api/v1/admin/operations/summary'),refetchInterval:15000})
 const trends=useQuery({queryKey:['ops-trends',range],queryFn:()=>api<any>(`/api/v1/admin/operations/trends?range=${range}`),refetchInterval:30000})
 const slow=useQuery({queryKey:['ops-slow'],queryFn:()=>api<any[]>('/api/v1/admin/operations/slow-endpoints'),refetchInterval:30000})
 const infra=useQuery({queryKey:['ops-infra'],queryFn:()=>api<any>('/api/v1/admin/operations/infrastructure'),refetchInterval:30000})
 const deps=useQuery({queryKey:['ops-deps'],queryFn:()=>api<any[]>('/api/v1/admin/operations/dependencies'),refetchInterval:30000})
 const incidents=useQuery({queryKey:['ops-incidents-pro'],queryFn:()=>api<any[]>('/api/v1/admin/operations/incidents'),refetchInterval:30000})
 const links=useQuery({queryKey:['ops-links-pro'],queryFn:()=>api<Record<string,string>>('/api/v1/admin/operations/links')})
 const corr=useQuery({queryKey:['ops-corr-pro',cid],enabled:cid.trim().length>0,queryFn:()=>api<any>(`/api/v1/admin/operations/correlation/${encodeURIComponent(cid.trim())}`)})
 const perf=summary.data?.performance??{},services=summary.data?.services??[]
 const counts=useMemo(()=>({critical:(incidents.data??[]).filter(x=>x.severity==='CRITICAL').length,warning:(incidents.data??[]).filter(x=>x.severity==='WARNING').length,info:(incidents.data??[]).filter(x=>x.severity==='INFO').length}),[incidents.data])
 const tabs=[
  {key:'overview',label:'نمای مدیریتی',children:<div className="sakhtyar-dashboard-grid">
   <Row gutter={[12,12]}>
    <Col xs={24} md={12} xl={6}><Card className="sakhtyar-kpi-card sakhtyar-kpi-primary"><Statistic title="وضعیت کل سامانه" value={summary.data?.status==='HEALTHY'?'سالم':summary.data?.status==='DEGRADED'?'کاهش کیفیت':'ناسالم'} prefix={<DashboardOutlined/>}/><div className="sakhtyar-kpi-foot">هسته و AI مبنای وضعیت کل هستند</div></Card></Col>
    <Col xs={24} md={12} xl={6}><Card className="sakhtyar-kpi-card"><Statistic title="نرخ درخواست" value={perf.requestRate??0} precision={2} suffix="/ثانیه"/><div className="sakhtyar-kpi-foot">RED · Rate</div></Card></Col>
    <Col xs={24} md={12} xl={6}><Card className="sakhtyar-kpi-card"><Statistic title="نرخ خطای 5xx" value={perf.errorRate??0} precision={2} suffix="٪"/><div className="sakhtyar-kpi-foot">RED · Errors</div></Card></Col>
    <Col xs={24} md={12} xl={6}><Card className="sakhtyar-kpi-card"><Statistic title="P95 زمان پاسخ" value={(perf.p95LatencySeconds??0)*1000} precision={0} suffix="ms"/><div className="sakhtyar-kpi-foot">RED · Duration</div></Card></Col>
   </Row>
   <Card><Row gutter={[16,16]}><Col xs={24} md={8}><div className="sakhtyar-health-domain"><strong>سلامت هسته</strong>{statusTag(summary.data?.coreStatus)}<small>API · PostgreSQL · Redis · MinIO</small></div></Col><Col xs={24} md={8}><div className="sakhtyar-health-domain"><strong>سلامت AI</strong>{statusTag(summary.data?.aiStatus)}<small>AI Provider</small></div></Col><Col xs={24} md={8}><div className="sakhtyar-health-domain"><strong>سلامت پایش</strong>{statusTag(summary.data?.observabilityStatus)}<small>Prometheus · Loki · Tempo · Grafana</small></div></Col></Row></Card>
   <div className="sakhtyar-dashboard-toolbar"><Typography.Title level={4} style={{margin:0}}>روند عملکرد</Typography.Title><Segmented value={range} onChange={v=>setRange(String(v))} options={[{label:'۱ ساعت',value:'1h'},{label:'۶ ساعت',value:'6h'},{label:'۲۴ ساعت',value:'24h'},{label:'۷ روز',value:'7d'}]}/></div>
   <Row gutter={[12,12]}><Col xs={24} xl={8}><MetricLineChart title="نرخ درخواست" subtitle="RED · Rate" unit="/s" points={trends.data?.requestRate??[]}/></Col><Col xs={24} xl={8}><MetricLineChart title="نرخ خطای 5xx" subtitle="RED · Errors" unit="%" points={trends.data?.errorRate??[]}/></Col><Col xs={24} xl={8}><MetricLineChart title="P95 زمان پاسخ" subtitle="RED · Duration" unit="s" points={trends.data?.p95LatencySeconds??[]}/></Col></Row>
   <Card title="نقشه سلامت سرویس‌ها"><div className="sakhtyar-service-map">{services.map((s:any)=><div key={s.name} className={`sakhtyar-service-node is-${String(s.status).toLowerCase()}`}><div className="sakhtyar-service-node-head"><strong>{s.name}</strong>{statusTag(s.status)}</div><span>{s.group==='CORE'?'هسته':s.group==='AI'?'هوش مصنوعی':'پایش'}</span><small>{s.latencyMs==null?'Latency —':`${s.latencyMs} ms`}</small></div>)}</div></Card>
  </div>},
  {key:'performance',label:'عملکرد',children:<Row gutter={[12,12]}><Col xs={24} xl={16}><Card title="کندترین Endpointها"><Table rowKey={(r:any,i?:number)=>`${r.method}-${r.uri}-${i}`} pagination={false} dataSource={slow.data??[]} columns={[{title:'متد',dataIndex:'method',width:90},{title:'Endpoint',dataIndex:'uri'},{title:'P95',dataIndex:'value',render:(v:number)=>v==null?'—':`${(v*1000).toFixed(0)} ms`}]}/></Card></Col><Col xs={24} xl={8}><Card title="Golden Signals"><Descriptions column={1}><Descriptions.Item label="Rate">{Number(perf.requestRate??0).toFixed(2)} /s</Descriptions.Item><Descriptions.Item label="Errors">{Number(perf.errorRate??0).toFixed(2)}%</Descriptions.Item><Descriptions.Item label="P95">{((perf.p95LatencySeconds??0)*1000).toFixed(0)} ms</Descriptions.Item><Descriptions.Item label="CPU">{perf.processCpuUsage==null?'—':`${(perf.processCpuUsage*100).toFixed(1)}%`}</Descriptions.Item></Descriptions></Card></Col></Row>},
  {key:'infra',label:'زیرساخت',children:<Row gutter={[12,12]}><Col xs={24} lg={12}><Card title="JVM و پردازش"><Descriptions column={1}><Descriptions.Item label="Heap مصرف‌شده">{mb(infra.data?.jvmHeapBytes)}</Descriptions.Item><Descriptions.Item label="Heap حداکثر">{mb(infra.data?.jvmMaxHeapBytes)}</Descriptions.Item><Descriptions.Item label="Thread فعال">{infra.data?.threadsLive??'—'}</Descriptions.Item><Descriptions.Item label="CPU">{infra.data?.processCpuUsage==null?'—':`${(infra.data.processCpuUsage*100).toFixed(1)}%`}</Descriptions.Item></Descriptions></Card></Col><Col xs={24} lg={12}><Card title="Connection Pool"><Descriptions column={1}><Descriptions.Item label="Active">{infra.data?.dbActiveConnections??'—'}</Descriptions.Item><Descriptions.Item label="Idle">{infra.data?.dbIdleConnections??'—'}</Descriptions.Item><Descriptions.Item label="Pending">{infra.data?.dbPendingConnections??'—'}</Descriptions.Item></Descriptions></Card></Col><Col span={24}><Card title="وابستگی‌های سرویس از Trace Metrics">{(deps.data??[]).length?<div className="sakhtyar-dependency-grid">{deps.data!.map((d:any,i:number)=><div className="sakhtyar-dependency-item" key={i}><strong>{d.client||'client'}</strong><span>←</span><strong>{d.server||'server'}</strong><Tag>{Number(d.value??0).toFixed(2)} req/s</Tag></div>)}</div>:<Empty description="Service Graph metric هنوز از Tempo/metrics-generator دریافت نشده است."/>}</Card></Col></Row>},
  {key:'incidents',label:'رخدادها و هشدارها',children:<div className="sakhtyar-dashboard-grid"><Row gutter={[12,12]}><Col xs={24} md={8}><Card><Statistic title="بحرانی" value={counts.critical} prefix={<ExclamationCircleOutlined/>}/></Card></Col><Col xs={24} md={8}><Card><Statistic title="هشدار" value={counts.warning} prefix={<WarningOutlined/>}/></Card></Col><Col xs={24} md={8}><Card><Statistic title="اطلاعاتی" value={counts.info} prefix={<CheckCircleOutlined/>}/></Card></Col></Row><Card title="مرکز رخدادها"><Table rowKey={(_:any,i?:number)=>String(i)} pagination={false} dataSource={incidents.data??[]} columns={[{title:'شدت',dataIndex:'severity',render:(v:string)=><Tag color={v==='CRITICAL'?'red':v==='WARNING'?'gold':'blue'}>{v==='CRITICAL'?'بحرانی':v==='WARNING'?'هشدار':'اطلاعاتی'}</Tag>},{title:'سرویس',dataIndex:'service'},{title:'عنوان',dataIndex:'title'},{title:'اثر',dataIndex:'impact'},{title:'جزئیات',dataIndex:'summary'}]}/></Card></div>},
  {key:'correlation',label:'رهگیری درخواست',children:<Row gutter={[12,12]}><Col xs={24} xl={9}><Card title="جست‌وجوی Correlation ID"><Typography.Paragraph type="secondary">X-Correlation-ID را وارد کنید تا لاگ‌های مرتبط و Trace IDهای قابل استخراج پیدا شوند.</Typography.Paragraph><Input value={cid} onChange={e=>setCid(e.target.value)} prefix={<SearchOutlined/>} allowClear placeholder="557e432c..."/>{corr.data?<Descriptions column={1} style={{marginTop:16}}><Descriptions.Item label="لاگ">{corr.data.logs?.length??0}</Descriptions.Item><Descriptions.Item label="Trace ID">{corr.data.traceIds?.length??0}</Descriptions.Item><Descriptions.Item label="Loki">{corr.data.logsAvailable?'در دسترس':'در دسترس نیست'}</Descriptions.Item><Descriptions.Item label="Tempo">{corr.data.tracesAvailable?'در دسترس':'در دسترس نیست'}</Descriptions.Item></Descriptions>:null}</Card></Col><Col xs={24} xl={15}><Card title="لاگ‌های مرتبط">{(corr.data?.logs??[]).length?<Table size="small" pagination={{pageSize:8}} rowKey={(_:any,i?:number)=>String(i)} dataSource={corr.data.logs} columns={[{title:'سطح',dataIndex:'level',width:90},{title:'پیام',dataIndex:'message'},{title:'Trace ID',dataIndex:'traceId',width:220}]}/>:<Empty description="پس از وارد کردن شناسه معتبر، لاگ‌ها اینجا نمایش داده می‌شوند."/>}</Card></Col></Row>}
 ]
 return <div className="sakhtyar-page-stack"><Card className="sakhtyar-dashboard-hero"><Space style={{width:'100%',justifyContent:'space-between'}} align="start" wrap><div><Typography.Title level={2} style={{margin:0}}>مرکز عملیات ساخت‌یار</Typography.Title><Typography.Paragraph type="secondary" style={{marginBottom:0}}>سلامت، عملکرد، زیرساخت، رخداد و Observability</Typography.Paragraph></div><Space wrap><Button icon={<ReloadOutlined/>} onClick={()=>summary.refetch()}>به‌روزرسانی</Button>{links.data?.grafana?<Button icon={<LinkOutlined/>} onClick={()=>window.open(links.data!.grafana,'_blank','noopener,noreferrer')}>باز کردن Grafana</Button>:null}<ContextHelpButton titleFa="راهنمای جامع مرکز عملیات" titleEn="Operations Center Guide" tabs={helpTabs}/></Space></Space></Card>{summary.data?.observabilityStatus!=='HEALTHY'?<Alert showIcon type="warning" message="بخشی از ابزارهای پایش در دسترس نیست" description="این وضعیت لزوماً به معنی اختلال در هسته ساخت‌یار نیست. تب رخدادها را بررسی کنید."/>:null}<Tabs items={tabs}/></div>
}