package com.sakhtyar.config;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class PlatformConfigService {
 private final JdbcTemplate db; private final ConfigRegistry registry;
 public PlatformConfigService(JdbcTemplate db,ConfigRegistry registry){this.db=db;this.registry=registry;}
 public Map<String,Object> current(){var versions=db.queryForList("select id,version_number,status,environment,reason,created_at,published_at from platform_config_version order by version_number desc limit 30");var active=db.queryForList("select v.id,v.version_number,v.environment,v.published_at from platform_config_activation a join platform_config_version v on v.id=a.version_id where a.deactivated_at is null order by a.activated_at desc");return Map.of("definitions",registry.all(),"versions",versions,"active",active);}
 public List<Map<String,Object>> values(UUID id){return db.queryForList("select config_key,value_text,is_secret,scope_type,scope_key from platform_config_value where version_id=? order by config_key",id);}
 @Transactional public UUID draft(String env,String reason,String actor){Integer n=db.queryForObject("select coalesce(max(version_number),0)+1 from platform_config_version",Integer.class);UUID id=UUID.randomUUID();db.update("insert into platform_config_version(id,version_number,status,environment,reason,created_by) values (?,?, 'DRAFT',?,?,?)",id,n,env,reason,actor);return id;}
 @Transactional public void put(UUID id,String key,String value,String scopeType,String scopeKey,String actor){var d=registry.find(key).orElseThrow(()->new IllegalArgumentException("Unknown config: "+key));String stored=d.secret()?null:value;String fp=d.secret()&&value!=null?Integer.toHexString(value.hashCode()):null;db.update("insert into platform_config_value(version_id,config_key,value_text,is_secret,secret_fingerprint,scope_type,scope_key,updated_by) values (?,?,?,?,?,?,?,?) on conflict(version_id,config_key,scope_type,scope_key) do update set value_text=excluded.value_text,is_secret=excluded.is_secret,secret_fingerprint=excluded.secret_fingerprint,updated_by=excluded.updated_by,updated_at=now()",id,key,stored,d.secret(),fp,scopeType,scopeKey,actor);db.update("insert into platform_config_audit(version_id,actor,action,target_key,result) values (?,?, 'CONFIG_CHANGED',?,'SUCCESS')",id,actor,key);}
 @Transactional public void publish(UUID id,String actor){db.update("update platform_config_version set status='PUBLISHED',published_by=?,published_at=now() where id=? and status='DRAFT'",actor,id);String env=db.queryForObject("select environment from platform_config_version where id=?",String.class,id);db.update("update platform_config_activation set deactivated_at=now() where environment=? and deactivated_at is null",env);db.update("insert into platform_config_activation(version_id,environment,activated_by) values (?,?,?)",id,env,actor);db.update("insert into platform_config_audit(version_id,actor,action,result) values (?,?, 'PUBLISH','SUCCESS')",id,actor);}
}