import { Empty, Typography } from 'antd'
export type MetricPoint={timestamp?:number|string;bucket?:string;value:number}
function compact(v:number){const a=Math.abs(v);if(a>=1e9)return`${(v/1e9).toFixed(1)}B`;if(a>=1e6)return`${(v/1e6).toFixed(1)}M`;if(a>=1e3)return`${(v/1e3).toFixed(1)}K`;return v.toFixed(a<10?2:0)}
export function MetricLineChart({title,subtitle,points,unit='',height=180}:{title:string;subtitle?:string;points:MetricPoint[];unit?:string;height?:number}){
 const clean=points.filter(p=>Number.isFinite(Number(p.value)));if(clean.length<2)return <div className="sakhtyar-chart-card"><div><Typography.Text strong>{title}</Typography.Text>{subtitle?<div className="sakhtyar-chart-subtitle">{subtitle}</div>:null}</div><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="داده کافی برای نمودار وجود ندارد"/></div>
 const width=640,padX=28,padY=22,vals=clean.map(p=>Number(p.value)),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,Math.abs(max)*.05,.0001)
 const c=clean.map((p,i)=>({x:padX+(i/Math.max(1,clean.length-1))*(width-padX*2),y:padY+((max-Number(p.value))/span)*(height-padY*2)}))
 const path=c.map((p,i)=>`${i?'L':'M'} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' '),last=vals.at(-1)??0
 return <div className="sakhtyar-chart-card"><div className="sakhtyar-chart-header"><div><Typography.Text strong>{title}</Typography.Text>{subtitle?<div className="sakhtyar-chart-subtitle">{subtitle}</div>:null}</div><div className="sakhtyar-chart-value">{compact(last)} {unit}</div></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={title}><line x1={padX} x2={width-padX} y1={height-padY} y2={height-padY} className="sakhtyar-chart-axis"/><line x1={padX} x2={width-padX} y1={padY} y2={padY} className="sakhtyar-chart-grid"/><line x1={padX} x2={width-padX} y1={height/2} y2={height/2} className="sakhtyar-chart-grid"/><path d={path} fill="none" className="sakhtyar-chart-line"/><circle cx={c.at(-1)!.x} cy={c.at(-1)!.y} r="5" className="sakhtyar-chart-dot"/><text x={padX} y={15} className="sakhtyar-chart-label">{compact(max)}</text><text x={padX} y={height-4} className="sakhtyar-chart-label">{compact(min)}</text></svg></div>
}